/* +++++ BASE DE DATOS DE PROYECTO SARC +++++ */
CREATE DATABASE sarc_db;

USE sarc_db;

-- ++++++++++++++++++++++ #1 TABLA DE ROLES +++++++++++++++++++++++++++++

CREATE TABLE IF NOT EXISTS ROLES
(
    ROL_CODIGO         INT PRIMARY KEY AUTO_INCREMENT COMMENT 'CODIGO E IDENTIFICADOR UNICO DEL ROL',
    ROL_NOMBRE         VARCHAR(100) NOT NULL COMMENT 'NOMBRE DEL ROL',
    ROL_FECHA_REGISTRO TIMESTAMP    NULL     DEFAULT (CURRENT_TIMESTAMP) COMMENT 'GUARDAR EL DATO DE CREACION DEL ROL',
    ROL_FUM            TIMESTAMP    NULL     DEFAULT (CURRENT_TIMESTAMP) COMMENT 'GUARDAR LA FECHA DE LA ULTIMA MODIFICACION HECHA AL ROL',
    ROL_ESTADO         VARCHAR(20)  NOT NULL DEFAULT ('ACTIVO') COMMENT 'ACTIVO; INACTIVO'
) ENGINE = INNODB;


-- ++++++++++++++++++++++ #2 TABLA DE USUARIOS +++++++++++++++++++++++++++++

CREATE TABLE IF NOT EXISTS USUARIOS
(
    USU_CODIGO         INT PRIMARY KEY AUTO_INCREMENT COMMENT 'CODIGO E IDENTIFICADOR UNICO DEL USUARIO',
    USU_ROL_ID         INT          NOT NULL COMMENT 'EL CODIGO DEL ROL AL QUE SE ASOCIA ESTE USUARIO FOREIGN KEY',
    USU_USERNAME       VARCHAR(100) NOT NULL UNIQUE COMMENT 'NOMBRE DEL USUARIO UNICO',
    USU_EMAIL          VARCHAR(200) NOT NULL UNIQUE COMMENT 'EMAIL DEL USUARIO UNICO',
    USU_CLAVE          VARCHAR(100) NOT NULL COMMENT 'LA CLAVE ENCRIPTADA DEL USUARIO',
    USU_FECHA_REGISTRO TIMESTAMP    NULL     DEFAULT (CURRENT_TIMESTAMP) COMMENT 'GUARDAR EL DATO DE CREACION DEL USUARIO',
    USU_FUM            TIMESTAMP    NULL     DEFAULT (CURRENT_TIMESTAMP) COMMENT 'GUARDAR LA FECHA DE LA ULTIMA MODIFICACION HECHA AL USUARIO',
    USU_ESTADO         VARCHAR(20)  NOT NULL DEFAULT ('ACTIVO') COMMENT 'ACTIVO; INACTIVO',
    CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (USU_ROL_ID)
        REFERENCES ROLES (ROL_CODIGO)
) ENGINE = INNODB;

-- +++++++++++++++++++++++++++++++ #3 TABLA DE CLIENTES +++++++++++++++++++++++++++++++

CREATE TABLE IF NOT EXISTS CLIENTES
(
    CLI_CODIGO      INT PRIMARY KEY AUTO_INCREMENT COMMENT 'CODIGO UNICO DEL CLIENTE',
    CLI_USUARIO_ID  INT         NOT NULL COMMENT 'CODIGO UNICO AL QUE SE LE HACE REFENCIA (FK)',
    CLI_FECHA_NAC   DATE        NOT NULL COMMENT 'LA FECHA DE NACIMENTO DEL CLIENTE',
    CLI_PRIMER_NOM  VARCHAR(60) NOT NULL COMMENT 'NOMBRE 1 DEL CLIENTE, ESTE ES UN CAMPO OBLIGATORIO',
    CLI_SEGUNDO_NOM VARCHAR(60) NULL COMMENT 'NOMBRE 2 DEL CLIENTE, ESTE ES UN CAMPO QUE PUEDE SER NULL, YA QUE HAY QUIENES SOLO TIENE UN NOMBRE',
    CLI_PRIMER_APE  VARCHAR(60) NOT NULL COMMENT 'APELLIDO 1 DEL CLIENTE, ESTE ES UN CAMPO OBLIGATORIO',
    CLI_SEGUNDO_APE VARCHAR(60) NULL COMMENT 'APELLIDO 2 DEL CLIENTE, ESTE ES UN CAMPO QUE PUEDE SER NULL, YA QUE HAY QUIENES SOLO TIENE UN APELLIDO',
    CLI_TELEFONO    VARCHAR(10) NULL COMMENT 'EL NUMERO DE CONTACTO DEL CLIENTE, PUEDE SER NULL, PERO NO RECOMENDADO',
    CLI_DUI         VARCHAR(10) NULL COMMENT 'EL NUMERO DE IDENTIFICACIÓN ÚNICO DEL CLIENTE',
    CLI_ESTADO      VARCHAR(20) NOT NULL DEFAULT ('ACTIVO') COMMENT 'ACTIVO; INACTIVO',
    CONSTRAINT FK_CLIENTE_USUARIO FOREIGN KEY (CLI_USUARIO_ID)
        REFERENCES USUARIOS (USU_CODIGO) ON DELETE CASCADE -- SI EL CLIENTO LO ELIMINO, QUE SE ELIMINE TAMBIEN EL USUARIO
) ENGINE = INNODB;